/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.brokechef.recipesharingapp.data.models

import com.brokechef.recipesharingapp.data.models.RecipesFindAll400ResponseIssuesInner

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param message 
 * @param code 
 * @param issues 
 */
@Serializable

data class RecipesFindAll400Response (

    @SerialName(value = "message")
    val message: kotlin.String?,

    @SerialName(value = "code")
    val code: kotlin.String?,

    @SerialName(value = "issues")
    val issues: kotlin.collections.List<RecipesFindAll400ResponseIssuesInner>? = null

) {


}

