/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.brokechef.recipesharingapp.data.models.openapi


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param userId 
 * @param title 
 * @param createdAt 
 * @param updatedAt 
 * @param imageUrl 
 */
@Serializable

data class CollectionsCreate200Response (

    @SerialName(value = "id")
    val id: kotlin.Int,

    @SerialName(value = "userId")
    val userId: kotlin.String,

    @SerialName(value = "title")
    val title: kotlin.String,

    @SerialName(value = "createdAt")
    val createdAt: kotlin.String = "2026-02-25T22:52:34.511Z",

    @SerialName(value = "updatedAt")
    val updatedAt: kotlin.String = "2026-02-25T22:52:34.511Z",

    @SerialName(value = "imageUrl")
    val imageUrl: kotlin.String? = null

) {


}

