/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.brokechef.recipesharingapp.data.models.openapi


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param title 
 * @param imageUrl 
 */
@Serializable

data class CollectionsCreateRequest (

    @SerialName(value = "title")
    val title: kotlin.String,

    @SerialName(value = "imageUrl")
    val imageUrl: kotlin.String? = null

) {


}

