/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.brokechef.recipesharingapp.data.models.openapi


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param followerId 
 * @param followedId 
 * @param createdAt 
 */
@Serializable

data class FollowsFollow200Response (

    @SerialName(value = "followerId")
    val followerId: kotlin.String,

    @SerialName(value = "followedId")
    val followedId: kotlin.String,

    @SerialName(value = "createdAt")
    val createdAt: kotlin.String = "2026-02-15T12:49:58.355Z"

) {


}

