/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.brokechef.recipesharingapp.data.models.openapi


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param recipeId 
 * @param rating 
 */
@Serializable

data class RatingsRateRequest (

    @SerialName(value = "recipeId")
    val recipeId: kotlin.Int,

    @SerialName(value = "rating")
    val rating: kotlin.Int

) {


}

