/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.brokechef.recipesharingapp.data.models.openapi


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param title 
 * @param duration 
 * @param steps 
 * @param ingredients 
 * @param tools 
 * @param imageUrl 
 */
@Serializable

data class RecipesCreateRequest (

    @SerialName(value = "title")
    val title: kotlin.String,

    @SerialName(value = "duration")
    val duration: kotlin.Int,

    @SerialName(value = "steps")
    val steps: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "ingredients")
    val ingredients: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "tools")
    val tools: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "imageUrl")
    val imageUrl: kotlin.String? = null

) {


}

