/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package com.brokechef.recipesharingapp.data.models.openapi

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param id
 * @param userId
 * @param title
 * @param duration
 * @param createdAt
 * @param author
 * @param imageUrl
 * @param steps
 * @param rating
 */
@Serializable
data class RecipesFindAll200ResponseInner(
    @SerialName(value = "id")
    val id: Int,
    @SerialName(value = "userId")
    val userId: String,
    @SerialName(value = "title")
    val title: String,
    @SerialName(value = "duration")
    val duration: Int,
    @SerialName(value = "createdAt")
    val createdAt: String = "2026-02-12T17:56:11.493Z",
    @SerialName(value = "author")
    val author: RecipesFindAll200ResponseInnerAuthor,
    @SerialName(value = "imageUrl")
    val imageUrl: String?,
    @SerialName(value = "steps")
    val steps: String,
    @SerialName(value = "rating")
    val rating: Int? = null,
)
