/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.brokechef.recipesharingapp.data.models.openapi

import com.brokechef.recipesharingapp.data.models.openapi.RecipesFindAll200ResponseInnerAuthor

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param userId 
 * @param title 
 * @param duration 
 * @param createdAt 
 * @param author 
 * @param steps 
 * @param imageUrl 
 * @param rating 
 */
@Serializable

data class RecipesFindAll200ResponseInner (

    @SerialName(value = "id")
    val id: kotlin.Int,

    @SerialName(value = "userId")
    val userId: kotlin.String,

    @SerialName(value = "title")
    val title: kotlin.String,

    @SerialName(value = "duration")
    val duration: kotlin.Int,

    @SerialName(value = "createdAt")
    val createdAt: kotlin.String = "2026-02-11T17:47:07.925Z",

    @SerialName(value = "author")
    val author: RecipesFindAll200ResponseInnerAuthor,

    @SerialName(value = "steps")
    val steps: kotlin.String,

    @SerialName(value = "imageUrl")
    val imageUrl: kotlin.String,

    @SerialName(value = "rating")
    val rating: kotlin.Int? = null

) {


}

