/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.brokechef.recipesharingapp.data.models.openapi


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param recipeId 
 * @param userId 
 * @param createdAt 
 */
@Serializable

data class SavedRecipesSave200Response (

    @SerialName(value = "recipeId")
    val recipeId: kotlin.Int,

    @SerialName(value = "userId")
    val userId: kotlin.String,

    @SerialName(value = "createdAt")
    val createdAt: kotlin.String = "2026-02-13T20:49:33.908Z"

) {


}

