/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.brokechef.recipesharingapp.data.models.openapi

import com.brokechef.recipesharingapp.data.models.openapi.RecipesSearch200ResponseInner

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param created 
 * @param saved 
 */
@Serializable

data class UsersGetRecipes200Response (

    @SerialName(value = "created")
    val created: kotlin.collections.List<RecipesSearch200ResponseInner>,

    @SerialName(value = "saved")
    val saved: kotlin.collections.List<RecipesSearch200ResponseInner>

) {


}

