/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.brokechef.recipesharingapp.api

import com.brokechef.recipesharingapp.data.models.openapi.CollectionsCreate200Response
import com.brokechef.recipesharingapp.data.models.openapi.CollectionsCreateRequest
import com.brokechef.recipesharingapp.data.models.openapi.CollectionsFindByUserId200ResponseInner
import com.brokechef.recipesharingapp.data.models.openapi.RecipesCreate400Response
import com.brokechef.recipesharingapp.data.models.openapi.RecipesSearch200ResponseInner

import org.openapitools.client.infrastructure.*
import io.ktor.client.HttpClientConfig
import io.ktor.client.request.forms.formData
import io.ktor.client.engine.HttpClientEngine
import io.ktor.http.ParametersBuilder

    open class CollectionsApi(
    baseUrl: String = ApiClient.BASE_URL,
    httpClientEngine: HttpClientEngine? = null,
    httpClientConfig: ((HttpClientConfig<*>) -> Unit)? = null,
    ) : ApiClient(
        baseUrl,
        httpClientEngine,
        httpClientConfig,
    ) {

        /**
        * POST /collections/create
        * Create a collection
        * 
         * @param collectionsCreateRequest  
         * @return CollectionsCreate200Response
        */
            @Suppress("UNCHECKED_CAST")
        open suspend fun collectionsCreate(collectionsCreateRequest: CollectionsCreateRequest): HttpResponse<CollectionsCreate200Response> {

            val localVariableAuthNames = listOf<String>("Authorization")

            val localVariableBody = collectionsCreateRequest

            val localVariableQuery = mutableMapOf<String, List<String>>()

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.POST,
            "/collections/create",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            )

            return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        /**
        * GET /collections/findById/{id}
        * Find collection by ID
        * 
         * @param id  
         * @return CollectionsCreate200Response
        */
            @Suppress("UNCHECKED_CAST")
        open suspend fun collectionsFindById(id: kotlin.Int): HttpResponse<CollectionsCreate200Response> {

            val localVariableAuthNames = listOf<String>("Authorization")

            val localVariableBody = 
                    io.ktor.client.utils.EmptyContent

            val localVariableQuery = mutableMapOf<String, List<String>>()

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/collections/findById/{id}".replace("{" + "id" + "}", "$id"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            )

            return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        /**
        * GET /collections/findByUserId
        * Get all collections by the user
        * 
         * @param userId  (optional)
         * @return kotlin.collections.List<CollectionsFindByUserId200ResponseInner>
        */
            @Suppress("UNCHECKED_CAST")
        open suspend fun collectionsFindByUserId(userId: kotlin.String?): HttpResponse<kotlin.collections.List<CollectionsFindByUserId200ResponseInner>> {

            val localVariableAuthNames = listOf<String>("Authorization")

            val localVariableBody = 
                    io.ktor.client.utils.EmptyContent

            val localVariableQuery = mutableMapOf<String, List<String>>()
            userId?.apply { localVariableQuery["userId"] = listOf("$userId") }

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/collections/findByUserId",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            )

            return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        /**
        * GET /collections/findRecipesByCollectionId/{id}
        * Find all recipes in the collection
        * 
         * @param id  
         * @return kotlin.collections.List<RecipesSearch200ResponseInner>
        */
            @Suppress("UNCHECKED_CAST")
        open suspend fun collectionsFindRecipesByCollectionId(id: kotlin.Int): HttpResponse<kotlin.collections.List<RecipesSearch200ResponseInner>> {

            val localVariableAuthNames = listOf<String>("Authorization")

            val localVariableBody = 
                    io.ktor.client.utils.EmptyContent

            val localVariableQuery = mutableMapOf<String, List<String>>()

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/collections/findRecipesByCollectionId/{id}".replace("{" + "id" + "}", "$id"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            )

            return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        /**
        * DELETE /collections/{id}
        * Deletes the collection
        * 
         * @param id  
         * @return kotlin.Any
        */
            @Suppress("UNCHECKED_CAST")
        open suspend fun collectionsRemove(id: kotlin.Int): HttpResponse<kotlin.Any> {

            val localVariableAuthNames = listOf<String>("Authorization")

            val localVariableBody = 
                    io.ktor.client.utils.EmptyContent

            val localVariableQuery = mutableMapOf<String, List<String>>()

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.DELETE,
            "/collections/{id}".replace("{" + "id" + "}", "$id"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            )

            return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        /**
        * GET /collections/totalCount
        * Get total count of collections for user
        * 
         * @param userId  (optional)
         * @return kotlin.Int
        */
            @Suppress("UNCHECKED_CAST")
        open suspend fun collectionsTotalCollectionsByUser(userId: kotlin.String?): HttpResponse<kotlin.Int> {

            val localVariableAuthNames = listOf<String>("Authorization")

            val localVariableBody = 
                    io.ktor.client.utils.EmptyContent

            val localVariableQuery = mutableMapOf<String, List<String>>()
            userId?.apply { localVariableQuery["userId"] = listOf("$userId") }

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/collections/totalCount",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            )

            return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        }
