/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.brokechef.recipesharingapp.api

import com.brokechef.recipesharingapp.data.models.openapi.CollectionsRecipesSave200Response
import com.brokechef.recipesharingapp.data.models.openapi.CollectionsRecipesSaveRequest
import com.brokechef.recipesharingapp.data.models.openapi.RecipesCreate400Response

import org.openapitools.client.infrastructure.*
import io.ktor.client.HttpClientConfig
import io.ktor.client.request.forms.formData
import io.ktor.client.engine.HttpClientEngine
import io.ktor.http.ParametersBuilder

    open class CollectionsRecipesApi(
    baseUrl: String = ApiClient.BASE_URL,
    httpClientEngine: HttpClientEngine? = null,
    httpClientConfig: ((HttpClientConfig<*>) -> Unit)? = null,
    ) : ApiClient(
        baseUrl,
        httpClientEngine,
        httpClientConfig,
    ) {

        /**
        * POST /collectionsRecipes
        * Save a recipe to collection
        * 
         * @param collectionsRecipesSaveRequest  
         * @return CollectionsRecipesSave200Response
        */
            @Suppress("UNCHECKED_CAST")
        open suspend fun collectionsRecipesSave(collectionsRecipesSaveRequest: CollectionsRecipesSaveRequest): HttpResponse<CollectionsRecipesSave200Response> {

            val localVariableAuthNames = listOf<String>("Authorization")

            val localVariableBody = collectionsRecipesSaveRequest

            val localVariableQuery = mutableMapOf<String, List<String>>()

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.POST,
            "/collectionsRecipes",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            )

            return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        /**
        * DELETE /collectionsRecipes
        * Remove recipe from collection
        * 
         * @param collectionId  
         * @param recipeId  
         * @return kotlin.Any
        */
            @Suppress("UNCHECKED_CAST")
        open suspend fun collectionsRecipesUnsave(collectionId: kotlin.Int, recipeId: kotlin.Int): HttpResponse<kotlin.Any> {

            val localVariableAuthNames = listOf<String>("Authorization")

            val localVariableBody = 
                    io.ktor.client.utils.EmptyContent

            val localVariableQuery = mutableMapOf<String, List<String>>()
            collectionId?.apply { localVariableQuery["collectionId"] = listOf("$collectionId") }
            recipeId?.apply { localVariableQuery["recipeId"] = listOf("$recipeId") }

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.DELETE,
            "/collectionsRecipes",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            )

            return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        }
