/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.brokechef.recipesharingapp.api

import com.brokechef.recipesharingapp.data.models.openapi.FollowsFollow200Response
import com.brokechef.recipesharingapp.data.models.openapi.FollowsFollowRequest
import com.brokechef.recipesharingapp.data.models.openapi.RecipesCreate400Response
import com.brokechef.recipesharingapp.data.models.openapi.UsersFindById200Response

import org.openapitools.client.infrastructure.*
import io.ktor.client.HttpClientConfig
import io.ktor.client.request.forms.formData
import io.ktor.client.engine.HttpClientEngine
import io.ktor.http.ParametersBuilder

    open class FollowsApi(
    baseUrl: String = ApiClient.BASE_URL,
    httpClientEngine: HttpClientEngine? = null,
    httpClientConfig: ((HttpClientConfig<*>) -> Unit)? = null,
    ) : ApiClient(
        baseUrl,
        httpClientEngine,
        httpClientConfig,
    ) {

        /**
        * POST /follows/create
        * Follow the user
        * 
         * @param followsFollowRequest  
         * @return FollowsFollow200Response
        */
            @Suppress("UNCHECKED_CAST")
        open suspend fun followsFollow(followsFollowRequest: FollowsFollowRequest): HttpResponse<FollowsFollow200Response> {

            val localVariableAuthNames = listOf<String>("Authorization")

            val localVariableBody = followsFollowRequest

            val localVariableQuery = mutableMapOf<String, List<String>>()

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.POST,
            "/follows/create",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            )

            return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        /**
        * GET /follows/getFollowers
        * Get all the followers that the user has
        * 
         * @param userId  (optional)
         * @return kotlin.collections.List<UsersFindById200Response>
        */
            @Suppress("UNCHECKED_CAST")
        open suspend fun followsGetFollowers(userId: kotlin.String?): HttpResponse<kotlin.collections.List<UsersFindById200Response>> {

            val localVariableAuthNames = listOf<String>("Authorization")

            val localVariableBody = 
                    io.ktor.client.utils.EmptyContent

            val localVariableQuery = mutableMapOf<String, List<String>>()
            userId?.apply { localVariableQuery["userId"] = listOf("$userId") }

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/follows/getFollowers",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            )

            return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        /**
        * GET /follows/getFollowing
        * Get all the users that user is following
        * 
         * @param userId  (optional)
         * @return kotlin.collections.List<UsersFindById200Response>
        */
            @Suppress("UNCHECKED_CAST")
        open suspend fun followsGetFollowing(userId: kotlin.String?): HttpResponse<kotlin.collections.List<UsersFindById200Response>> {

            val localVariableAuthNames = listOf<String>("Authorization")

            val localVariableBody = 
                    io.ktor.client.utils.EmptyContent

            val localVariableQuery = mutableMapOf<String, List<String>>()
            userId?.apply { localVariableQuery["userId"] = listOf("$userId") }

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/follows/getFollowing",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            )

            return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        /**
        * GET /follows/isFollowing
        * Check if the user is following the given user
        * 
         * @param userId  
         * @return kotlin.Boolean
        */
            @Suppress("UNCHECKED_CAST")
        open suspend fun followsIsFollowing(userId: kotlin.String): HttpResponse<kotlin.Boolean> {

            val localVariableAuthNames = listOf<String>("Authorization")

            val localVariableBody = 
                    io.ktor.client.utils.EmptyContent

            val localVariableQuery = mutableMapOf<String, List<String>>()
            userId?.apply { localVariableQuery["userId"] = listOf("$userId") }

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/follows/isFollowing",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            )

            return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        /**
        * GET /follows/totalFollowers
        * Get the total count of total followers that the user has
        * 
         * @param userId  (optional)
         * @return kotlin.Int
        */
            @Suppress("UNCHECKED_CAST")
        open suspend fun followsTotalFollowers(userId: kotlin.String?): HttpResponse<kotlin.Int> {

            val localVariableAuthNames = listOf<String>("Authorization")

            val localVariableBody = 
                    io.ktor.client.utils.EmptyContent

            val localVariableQuery = mutableMapOf<String, List<String>>()
            userId?.apply { localVariableQuery["userId"] = listOf("$userId") }

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/follows/totalFollowers",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            )

            return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        /**
        * GET /follows/totalFollowing
        * Get the total count of total users that the user is following
        * 
         * @param userId  (optional)
         * @return kotlin.Int
        */
            @Suppress("UNCHECKED_CAST")
        open suspend fun followsTotalFollowing(userId: kotlin.String?): HttpResponse<kotlin.Int> {

            val localVariableAuthNames = listOf<String>("Authorization")

            val localVariableBody = 
                    io.ktor.client.utils.EmptyContent

            val localVariableQuery = mutableMapOf<String, List<String>>()
            userId?.apply { localVariableQuery["userId"] = listOf("$userId") }

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/follows/totalFollowing",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            )

            return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        /**
        * DELETE /follows/remove
        * Unfollow user
        * 
         * @param userId  
         * @return kotlin.Any
        */
            @Suppress("UNCHECKED_CAST")
        open suspend fun followsUnfollow(userId: kotlin.String): HttpResponse<kotlin.Any> {

            val localVariableAuthNames = listOf<String>("Authorization")

            val localVariableBody = 
                    io.ktor.client.utils.EmptyContent

            val localVariableQuery = mutableMapOf<String, List<String>>()
            userId?.apply { localVariableQuery["userId"] = listOf("$userId") }

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.DELETE,
            "/follows/remove",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            )

            return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        }
