/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.brokechef.recipesharingapp.api

import com.brokechef.recipesharingapp.data.models.openapi.RatingsRate200Response
import com.brokechef.recipesharingapp.data.models.openapi.RatingsRateRequest
import com.brokechef.recipesharingapp.data.models.openapi.RecipesCreate400Response

import org.openapitools.client.infrastructure.*
import io.ktor.client.HttpClientConfig
import io.ktor.client.request.forms.formData
import io.ktor.client.engine.HttpClientEngine
import io.ktor.http.ParametersBuilder

    open class RatingsApi(
    baseUrl: String = ApiClient.BASE_URL,
    httpClientEngine: HttpClientEngine? = null,
    httpClientConfig: ((HttpClientConfig<*>) -> Unit)? = null,
    ) : ApiClient(
        baseUrl,
        httpClientEngine,
        httpClientConfig,
    ) {

        /**
        * GET /ratings/{id}
        * Get user rating for the recipe
        * 
         * @param id  
         * @return kotlin.Int
        */
            @Suppress("UNCHECKED_CAST")
        open suspend fun ratingsGetUserRatingForRecipe(id: kotlin.Int): HttpResponse<kotlin.Int> {

            val localVariableAuthNames = listOf<String>("Authorization")

            val localVariableBody = 
                    io.ktor.client.utils.EmptyContent

            val localVariableQuery = mutableMapOf<String, List<String>>()

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/ratings/{id}".replace("{" + "id" + "}", "$id"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            )

            return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        /**
        * POST /ratings/create
        * Rate recipe
        * 
         * @param ratingsRateRequest  
         * @return RatingsRate200Response
        */
            @Suppress("UNCHECKED_CAST")
        open suspend fun ratingsRate(ratingsRateRequest: RatingsRateRequest): HttpResponse<RatingsRate200Response> {

            val localVariableAuthNames = listOf<String>("Authorization")

            val localVariableBody = ratingsRateRequest

            val localVariableQuery = mutableMapOf<String, List<String>>()

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.POST,
            "/ratings/create",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            )

            return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        /**
        * DELETE /ratings/{id}
        * Remove rating for recipe
        * 
         * @param id  
         * @return kotlin.Int
        */
            @Suppress("UNCHECKED_CAST")
        open suspend fun ratingsRemove(id: kotlin.Int): HttpResponse<kotlin.Int> {

            val localVariableAuthNames = listOf<String>("Authorization")

            val localVariableBody = 
                    io.ktor.client.utils.EmptyContent

            val localVariableQuery = mutableMapOf<String, List<String>>()

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.DELETE,
            "/ratings/{id}".replace("{" + "id" + "}", "$id"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            )

            return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        /**
        * PATCH /ratings/update
        * Update rating for recipe
        * 
         * @param ratingsRateRequest  
         * @return kotlin.Int
        */
            @Suppress("UNCHECKED_CAST")
        open suspend fun ratingsUpdate(ratingsRateRequest: RatingsRateRequest): HttpResponse<kotlin.Int> {

            val localVariableAuthNames = listOf<String>("Authorization")

            val localVariableBody = ratingsRateRequest

            val localVariableQuery = mutableMapOf<String, List<String>>()

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.PATCH,
            "/ratings/update",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            )

            return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        }
