/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.brokechef.recipesharingapp.api

import com.brokechef.recipesharingapp.data.models.openapi.RecipesFindAll200ResponseInner
import com.brokechef.recipesharingapp.data.models.openapi.RecipesSearch200ResponseInner
import com.brokechef.recipesharingapp.data.models.openapi.RecipesSearch400Response

import org.openapitools.client.infrastructure.*
import io.ktor.client.HttpClientConfig
import io.ktor.client.request.forms.formData
import io.ktor.client.engine.HttpClientEngine
import io.ktor.http.ParametersBuilder

    open class RecipesApi(
    baseUrl: String = ApiClient.BASE_URL,
    httpClientEngine: HttpClientEngine? = null,
    httpClientConfig: ((HttpClientConfig<*>) -> Unit)? = null,
    ) : ApiClient(
        baseUrl,
        httpClientEngine,
        httpClientConfig,
    ) {

        /**
        * GET /recipes/all
        * Fetch all recipes
        * 
         * @param offset  (optional, default to 0)
         * @param limit  (optional, default to 5)
         * @param sort  (optional, default to Sort.newest)
         * @return kotlin.collections.List<RecipesFindAll200ResponseInner>
        */
            @Suppress("UNCHECKED_CAST")
        open suspend fun recipesFindAll(offset: kotlin.Int?, limit: kotlin.Int?, sort: kotlin.String?): HttpResponse<kotlin.collections.List<RecipesFindAll200ResponseInner>> {

            val localVariableAuthNames = listOf<String>("Authorization")

            val localVariableBody = 
                    io.ktor.client.utils.EmptyContent

            val localVariableQuery = mutableMapOf<String, List<String>>()
            offset?.apply { localVariableQuery["offset"] = listOf("$offset") }
            limit?.apply { localVariableQuery["limit"] = listOf("$limit") }
            sort?.apply { localVariableQuery["sort"] = listOf("$sort") }

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/recipes/all",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            )

            return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        /**
        * GET /recipes/search
        * Search recipes semantically
        * 
         * @param userInput  
         * @param offset  (optional, default to 0)
         * @param limit  (optional, default to 5)
         * @return kotlin.collections.List<RecipesSearch200ResponseInner>
        */
            @Suppress("UNCHECKED_CAST")
        open suspend fun recipesSearch(userInput: kotlin.String, offset: kotlin.Int?, limit: kotlin.Int?): HttpResponse<kotlin.collections.List<RecipesSearch200ResponseInner>> {

            val localVariableAuthNames = listOf<String>("Authorization")

            val localVariableBody = 
                    io.ktor.client.utils.EmptyContent

            val localVariableQuery = mutableMapOf<String, List<String>>()
            offset?.apply { localVariableQuery["offset"] = listOf("$offset") }
            limit?.apply { localVariableQuery["limit"] = listOf("$limit") }
            userInput?.apply { localVariableQuery["userInput"] = listOf("$userInput") }

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/recipes/search",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            )

            return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        /**
        * GET /recipes/totalCount
        * Get total count of recipes
        * 
         * @return kotlin.Int
        */
            @Suppress("UNCHECKED_CAST")
        open suspend fun recipesTotalCount(): HttpResponse<kotlin.Int> {

            val localVariableAuthNames = listOf<String>("Authorization")

            val localVariableBody = 
                    io.ktor.client.utils.EmptyContent

            val localVariableQuery = mutableMapOf<String, List<String>>()

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/recipes/totalCount",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            )

            return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        }
