/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.brokechef.recipesharingapp.api

import com.brokechef.recipesharingapp.data.models.openapi.RecipesCreate400Response
import com.brokechef.recipesharingapp.data.models.openapi.RecipesSearch200ResponseInner
import com.brokechef.recipesharingapp.data.models.openapi.UsersFindById200Response
import com.brokechef.recipesharingapp.data.models.openapi.UsersGetRecipes200Response
import com.brokechef.recipesharingapp.data.models.openapi.UsersUpdateImageRequest

import org.openapitools.client.infrastructure.*
import io.ktor.client.HttpClientConfig
import io.ktor.client.request.forms.formData
import io.ktor.client.engine.HttpClientEngine
import io.ktor.http.ParametersBuilder

    open class UsersApi(
    baseUrl: String = ApiClient.BASE_URL,
    httpClientEngine: HttpClientEngine? = null,
    httpClientConfig: ((HttpClientConfig<*>) -> Unit)? = null,
    ) : ApiClient(
        baseUrl,
        httpClientEngine,
        httpClientConfig,
    ) {

        /**
        * GET /users/findById
        * Get user by ID
        * 
         * @param userId  (optional)
         * @return UsersFindById200Response
        */
            @Suppress("UNCHECKED_CAST")
        open suspend fun usersFindById(userId: kotlin.String?): HttpResponse<UsersFindById200Response> {

            val localVariableAuthNames = listOf<String>("Authorization")

            val localVariableBody = 
                    io.ktor.client.utils.EmptyContent

            val localVariableQuery = mutableMapOf<String, List<String>>()
            userId?.apply { localVariableQuery["userId"] = listOf("$userId") }

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/users/findById",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            )

            return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        /**
        * GET /users/getCreatedRecipes
        * Get created recipes by the user
        * 
         * @param offset  (optional, default to 0)
         * @param limit  (optional, default to 5)
         * @param userId  (optional)
         * @return kotlin.collections.List<RecipesSearch200ResponseInner>
        */
            @Suppress("UNCHECKED_CAST")
        open suspend fun usersGetCreatedRecipes(offset: kotlin.Int?, limit: kotlin.Int?, userId: kotlin.String?): HttpResponse<kotlin.collections.List<RecipesSearch200ResponseInner>> {

            val localVariableAuthNames = listOf<String>("Authorization")

            val localVariableBody = 
                    io.ktor.client.utils.EmptyContent

            val localVariableQuery = mutableMapOf<String, List<String>>()
            offset?.apply { localVariableQuery["offset"] = listOf("$offset") }
            limit?.apply { localVariableQuery["limit"] = listOf("$limit") }
            userId?.apply { localVariableQuery["userId"] = listOf("$userId") }

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/users/getCreatedRecipes",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            )

            return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        /**
        * GET /users/getRecipes
        * Get all created and saved recipes by the user
        * 
         * @param offset  (optional, default to 0)
         * @param limit  (optional, default to 5)
         * @param userId  (optional)
         * @return UsersGetRecipes200Response
        */
            @Suppress("UNCHECKED_CAST")
        open suspend fun usersGetRecipes(offset: kotlin.Int?, limit: kotlin.Int?, userId: kotlin.String?): HttpResponse<UsersGetRecipes200Response> {

            val localVariableAuthNames = listOf<String>("Authorization")

            val localVariableBody = 
                    io.ktor.client.utils.EmptyContent

            val localVariableQuery = mutableMapOf<String, List<String>>()
            offset?.apply { localVariableQuery["offset"] = listOf("$offset") }
            limit?.apply { localVariableQuery["limit"] = listOf("$limit") }
            userId?.apply { localVariableQuery["userId"] = listOf("$userId") }

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/users/getRecipes",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            )

            return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        /**
        * GET /users/getSavedRecipes
        * Get saved recipes by the user
        * 
         * @param offset  (optional, default to 0)
         * @param limit  (optional, default to 5)
         * @param userId  (optional)
         * @return kotlin.collections.List<RecipesSearch200ResponseInner>
        */
            @Suppress("UNCHECKED_CAST")
        open suspend fun usersGetSavedRecipes(offset: kotlin.Int?, limit: kotlin.Int?, userId: kotlin.String?): HttpResponse<kotlin.collections.List<RecipesSearch200ResponseInner>> {

            val localVariableAuthNames = listOf<String>("Authorization")

            val localVariableBody = 
                    io.ktor.client.utils.EmptyContent

            val localVariableQuery = mutableMapOf<String, List<String>>()
            offset?.apply { localVariableQuery["offset"] = listOf("$offset") }
            limit?.apply { localVariableQuery["limit"] = listOf("$limit") }
            userId?.apply { localVariableQuery["userId"] = listOf("$userId") }

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/users/getSavedRecipes",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            )

            return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        /**
        * GET /users/totalCreated
        * Get total count of created recipes by the user
        * 
         * @param userId  (optional)
         * @return kotlin.Int
        */
            @Suppress("UNCHECKED_CAST")
        open suspend fun usersTotalCreated(userId: kotlin.String?): HttpResponse<kotlin.Int> {

            val localVariableAuthNames = listOf<String>("Authorization")

            val localVariableBody = 
                    io.ktor.client.utils.EmptyContent

            val localVariableQuery = mutableMapOf<String, List<String>>()
            userId?.apply { localVariableQuery["userId"] = listOf("$userId") }

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/users/totalCreated",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            )

            return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        /**
        * GET /users/totalSaved
        * Get total count of saved recipes by the user
        * 
         * @param userId  (optional)
         * @return kotlin.Int
        */
            @Suppress("UNCHECKED_CAST")
        open suspend fun usersTotalSaved(userId: kotlin.String?): HttpResponse<kotlin.Int> {

            val localVariableAuthNames = listOf<String>("Authorization")

            val localVariableBody = 
                    io.ktor.client.utils.EmptyContent

            val localVariableQuery = mutableMapOf<String, List<String>>()
            userId?.apply { localVariableQuery["userId"] = listOf("$userId") }

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/users/totalSaved",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            )

            return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        /**
        * PATCH /users/updateImage
        * Update image url
        * 
         * @param usersUpdateImageRequest  
         * @return kotlin.String
        */
            @Suppress("UNCHECKED_CAST")
        open suspend fun usersUpdateImage(usersUpdateImageRequest: UsersUpdateImageRequest): HttpResponse<kotlin.String> {

            val localVariableAuthNames = listOf<String>("Authorization")

            val localVariableBody = usersUpdateImageRequest

            val localVariableQuery = mutableMapOf<String, List<String>>()

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.PATCH,
            "/users/updateImage",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            )

            return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        }
